// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PFMBackend.Data;

#nullable disable

namespace PFMBackend.Migrations
{
    [DbContext(typeof(PFMDbContex))]
    partial class PFMDbContexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("PFMBackend.Models.Category", b =>
                {
                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("parent_code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PFMBackend.Models.Transaction", b =>
                {
                    b.Property<double>("amount")
                        .HasColumnType("REAL");

                    b.Property<string>("beneficiary_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mcc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
